#!/bin/bash

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

apt-get install -y "${APTGETOPT[@]}" lintian

# to avoid the following warning
# su: warning: cannot change directory to /nonexistent: No such file or directory
usermod --home "$BUILDDIR"/*/ pbuilder

echo "+++ lintian output +++"

#su -c "lintian -I --show-overrides "$BUILDDIR"/*.changes" - pbuilder
# use this version if you don't want lintian to fail the build
su -c "lintian --color=auto -iIEcv --pedantic --show-overrides "$BUILDDIR"/*.changes; :" - pbuilder

echo "+++ end of lintian output +++"

