#! /bin/bash

USAGE="usage: buildpkg <distribution> [--native|-n]"

# used to build packages on different dists
build()
{
    # set distribution
    _DIST_="${1}"

    # clean up the chroot directories
    pbuilder clean

    # update cowbuilder chroot
    HOME=$HOME DIST=${_DIST_} cowbuilder update

    # build the package
    if [[ $# = 1 ]]; then
        DIST=${_DIST_} debmake -y -t --invoke 'pdebuild --pbuilder cowbuilder -- --debbuildopts="-b"'
    elif [[ $# = 2 && ( $2 = "-n" || $2 = "--native" ) ]]; then
        DIST=${_DIST_} debmake -y -n --invoke 'pdebuild --pbuilder cowbuilder -- --debbuildopts="-b"'
    else
        echo "unrecognized argument: ${2}" 1>&2
        exit 1
    fi
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "$USAGE" 1>&2
    exit 1
fi

if [[ $(id -u) -ne 0 ]]; then
    echo "must be root" 1>&2
    exit 1
fi

if [[ ! -d ./debian ]]; then
    echo "you should be in directory above debian/ directory" 1>&2
    exit 1
fi

build "$@"
