#! /bin/bash

# pbuilder configuration
# read pbuilderrc.5 document for notes on specific options.

umask 0022

ARCH="amd64"
NAME="${DIST}-${ARCH}"
MIRRORSITE="http://deb.debian.org/debian/"
COMPONENTS="main contrib non-free"
DEBOOTSTRAPOPTS=( --arch="${ARCH}" "--force-check-gpg" "--no-merged-usr" "--variant=buildd" )
COMPRESSPROG="xz -9"
BASETGZ="/var/cache/pbuilder/base-${NAME}.tar.xz"
BASEPATH="/var/cache/pbuilder/base-${NAME}.cow"
DISTRIBUTION="${DIST}"
BUILDRESULT="/var/cache/pbuilder/${NAME}/result"
APTCACHE=""
BUILDPLACE="/var/cache/pbuilder/build/"
ALLOWUNTRUSTED="no"
DEBUILDOPTS="-i -b"
SIGN="${DEBEMAIL}"
LOGLEVEL="W"
USECOLORS="auto"
EXTRAPACKCAGES=${EXTRAPACKAGES}${EXTRAPACKAGES:+" "}"eatmydata"
EATMYDATA="yes"
CCACHEDIR="/var/cache/pbuilder/ccache"
AUTO_DEBSIGN="no"
PDEBUILD_PBUILDER="cowbuilder"
HOOKDIR="/usr/libexec/pbuilder/hooks"
USENETWORK=${ENABLE_NETWORKING:=no} # buildd has no network, best to keep this off
export DEBIAN_FRONTEND="noninteractive"
